name: Cypress Tests
run-name: Cypress Tests - [${{ inputs.CORRELATOR && inputs.CORRELATOR || 'N/A' }}]

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ENVTOTEST:
        description: 'What environment to test?'
        required: true
        default: 'stage'
        options:
          - 'stage'
          - 'prod'
      CORRELATOR:
        description: 'Correlator ID (for finding this run later)'
        required: false
        
jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: true # Runs test in parallel using settings above
          command: npx cypress run --config-file ${{ inputs.ENVTOTEST }}.config.js --record --key fbfe4024-3cbb-40a7-b666-3301baa763dd --spec cypress/e2e/instagram-tests.cy.js
          browser: electron
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          
