name: Cypress Tests
run-name: Cypress Tests - [${{ inputs.CORRELATOR && inputs.CORRELATOR || 'N/A' }}]

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ENVTOTEST:
        description: 'What environment to test?'
        required: true
        default: 'stage'
        options:
          - 'stage'
          - 'prod'
      CORRELATOR:
        description: 'Correlator ID (for finding this run later)'
        required: false
        
jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    #runs-on: generic
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Test
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --config-file ${{ inputs.ENVTOTEST }}.config.js
          browser: electron
        env:
          SPLIT: ${{ strategy.job-total}}
          SPLIT_INDEX: ${{ strategy.job-index}}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
